# Bootloader module configuration

---
efiBootLoader: "grub"

efiBootloaderId: "arbor"

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"

installEFIFallback: true

timeout: 10

kernel: "/vmlinuz-linux"
img: "/initramfs-linux.img"
fallback: "/initramfs-linux-fallback.img"

grubOptions:
    - "quiet"
    - "splash"
