# Partition module configuration

---
efiSystemPartition:     "/boot/efi"
userSwapChoices:
    - none
    - small
    - suspend
    - file

drawNestedPartitions:   false
alwaysShowPartitionLabels: true

defaultFileSystemType:  "ext4"

availableFileSystemTypes:
    - "ext4"
    - "btrfs"
    - "xfs"

initialPartitioningChoice: erase
initialSwapChoice: small

armInstall: false
