# Users module configuration

---
userShell: /bin/bash

defaultGroups:
    - users
    - wheel
    - audio
    - video
    - storage
    - optical
    - lp
    - scanner
    - power
    - network
    - input

autologinGroup:  autologin

doAutologin:     false

sudoersGroup:    wheel

setRootPassword: false
doReusePassword: false

allowWeakPasswords: false
allowWeakPasswordsDefault: false

user:
  shell: /bin/bash
  forbidden_names: [ root ]

hostname:
  location: EtcFile
  writeHostsFile: true
  template: "arbor-${cpu}"
  forbidden_names: [ localhost ]
